package symbol

const (
	Line              = "-"
	Comma             = ","
	Point             = "."
	Colon             = ":"
	CaesuraSign       = "、"
	Semicolon         = ";"
	QuestionMark      = "?"
	Vertical          = "|"
	Slash             = "/"
	SingleQuotes      = "'"
	DoubleQuotation   = "\""
	OpenParentheses   = "("
	CloseParentheses  = ")"
	OpenBracket       = "["
	CloseBracket      = "]"
	OpenBraces        = "{"
	CloseBraces       = "}"
	WildcardCharacter = "*"
	Space             = " "
	EmptyString       = ""
	EmptyJson         = "{}"
	Percent           = "%"
	Add               = "+"
	Underline         = "_"
	Equal             = "="
	SingleAnd         = "&"
	CommaColon        = "', '"
	BackTicks         = "`"
	LineBreak         = "\n"
	DollarSign        = "$"
	At                = "@"
)
